### ISSUE TITLE
Link to particular view (JobsMap, for example)?

### ISSUE THREAD

**Issue by mikerenfro** [rackslab/Slurm-web#182]
Is there any easy way to get a link to a particular slurm-web view? For example, making links from my HPC site documentation to the Jobs view is easy, as that's the default view. But clicking the JobsMap view doesn't show a different URL, so it's not obvious how to show that view automatically.

**Comment by mehdid** [comment]
Currently, not possible. But it could be indeed handy.

**Comment by rezib** [comment]
This is fixed in Slurm-web v3.0.0 where every pages have their own URL (ex: node page, job page, jobs with filters, etc).

The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
