### ISSUE TITLE
example of configs that work with no authorization?

### ISSUE THREAD

**Issue by KristinaPlazonic** [rackslab/Slurm-web#197]
I was trying to do a quick POC on a test cluster and use slurm-web to visualize jobs on the nodes. I really don't need any authorization (and I don't have ldap on the test cluster, think cluster in the cloud), but don't know what config to change from the default example. I tried authorization: disable, but that was not enough. What else do you need to disable authorization? (I.e. shortest path to a working example?)

Thank you!

**Comment by liuxiaopiao** [comment]
is there any update here.  We would like to try similar poc

**Comment by mehdid** [comment]
In your `restapi.conf`, you may set `authentication = disable` in the `[config]` section. Is that what your are looking for?

Otherwise, slurm-web has to find some information about UIDs with jobs in slurm's queue. So, it has to get this information somehow. It uses `pwd.getpwuid` call to get that information. If an LDAP backend is configured, `pwd` will use it.

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 for which the quick start guide is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Note that Slurm-web v3.0.0 supports guest mode without LDAP authentication. Feel free to ask questions in discussions Q&A sections if you need help.

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
