### ISSUE TITLE
Do not fail for all LDAP users when user_name_attribute is missing on some entries

### ISSUE THREAD

**Issue by rezib** [rackslab/Slurm-web#360]
_Originally posted by @nikolaussuess in https://github.com/rackslab/Slurm-web/discussions/359#discussioncomment-10892343_:

> The `user_name_attribute=uid` exists on our LDAP server, and it seems that it is only missing for the `administrator` user (and exists for all other users). However, when I use `user_name_attribute=uid`, then I get the following error:
> `MainThread: [ERROR] slurmweb.apps.ldap LDAP error: Unable to extract user uid from user entries`
> I suggest to ignore such users (with a warning) instead of failing for all users. However, setting `user_name_attribute=cn` works fine.

**Comment by rezib** [comment]
@nikolaussuess This is fixed with in RFL v1.1.0 with https://github.com/rackslab/RFL/issues/12. There is actually nothing to change in Slurm-web itself, then I close this issue. If you upgrade `python3-rfl-*` packages to the latest version on the gateway host, you should now get the expected behavior. Can you confirm?

**Comment by nikolaussuess** [comment]
@rezib
Thank you for your work on slurm-web!

I cannot confirm since I am no longer using slurm-web. I really appreciate your project and I think it has a lot of very nice features!!!

That said, it does not fully meet our needs (yet), particularly regarding the visibility of GPU availability. While slurm-web provides this information, it can be hard to find, and I wanted to display it clearly for users. I considered modifying slurm-web, but I lack experience with Vue.js and TypeScript ... so, I was faster with writing a small PHP dashboard myself ;-)

Thanks again for your help and contributions!

**Comment by rezib** [comment]
OK no problem! Just in case you missed it, you can [ask Rackslab](https://rackslab.io/en/contact/) a quotation to develop #258. This feature is quite simple, it might be less expensive that developing of your own in-house solution, especially in the long term regarding the maintenance cost to stay compatible with latest Slurm versions. Let me know if you change your mind!
